### ISSUE TITLE
Upgrade serialize-javascript to latest version

### ISSUE THREAD

**Issue by nathanfallet** [danielcherubini/js-to-string#17]
Because of security issues, it would be great to update serialize-javascript to latest version.

<img width="936" alt="image" src="https://user-images.githubusercontent.com/30439790/97988616-86b63c80-1ddd-11eb-86d2-13bfef36563b.png">

**Comment by danielcherubini** [comment]
Sure I can try and look at this later this week. Or you can open a PR and bump the version of that lib and run the tests.

**Comment by danielcherubini** [comment]
done, update to latest

**Comment by danielcherubini** [comment]
fixed in v0.4.7

**Comment by nathanfallet** [comment]
Reopening, the `npm update` command updated from `1.5.0` to `1.9.1`, not `3.1.0`. I need to take a look to update manually to this version...
Going to make a new PR with `3.1.0` to fix this security issue for real
